### PR TITLE
Reorganize buttons layout

### PR DESCRIPTION
**Pull request by vaishnavibn14**
Reorganize buttons layout.

Please find the screenshot attached.
Screenshot (25)

https://github.com/Alitindrawan24/Binary-Calculator/issues/48

### CODE REVIEW

**Comment by Alitindrawan24** [comment]
After merging mayor fix, conflict happen in this PR. Can you fix it ? @vaishnavibn14

**Comment by vaishnavibn14** [comment]
Can you please help me how can I get is resolved, I am doing it for the first time .

**Comment by vaishnavibn14** [comment]
Hi @Alitindrawan24 , I have resolved the conflict.

**Comment by Alitindrawan24** [comment]
> Hi @Alitindrawan24 , I have resolved the conflict. I have added the decimal button because of the conflict were there.
> 
> Screenshot (28)

Sorry but the conflict still exists on the PR

**Comment by vaishnavibn14** [comment]
Hi @Alitindrawan24 ,
conflict is resolved.

**Pull request merged**
