### PR TITLE
Update binaryCalculator.js

### PR DESCRIPTION
**Pull request by Pedrop19**

### CODE REVIEW

**Comment by Alitindrawan24** [comment]
The PR got conflict after I merge some PR, can you solve the conflict ?

**Comment by Pedrop19** [comment]
> The PR got conflict after I merge some PR, can you solve the conflict ?

I have reviewed the code, and I believe I have resolved the merging issues. However, please double-check to be 100% certain, as two heads are better than one.

**Comment by debghs** [comment]
@Pedrop19 my pr is also having a conflict as well. Could you please wait while I sort that out. Otherwise we would have more and more conflicts.

**Comment by Pedrop19** [comment]
> @Pedrop19 my pr is also having a conflict as well. Could you please wait while I sort that out. Otherwise we would have more and more conflicts.
> Of course

**Pull request closed without merging**
