### PR TITLE
Add Bitwise NOT Operator to Binary Calculator

### PR DESCRIPTION
**Pull request by Satyasn01**
Issue no : #79 

## Overview
This pull request introduces the Bitwise NOT operator  to the Binary Calculator, enabling the inversion of all bits of the current binary number displayed in the calculator. This feature enhances the calculator's functionality, making it more versatile and useful for educational purposes, debugging, and binary arithmetic tasks.

## Changes Made
- Added a new button labeled `NOT` in the UI to trigger the Bitwise NOT operation.
- Implemented the `bitwiseNOT()` function in the calculator's JavaScript file, which handles the inversion of binary digits.
- Updated the HTML and CSS to accommodate the new button while ensuring it matches the existing style and layout.

## Importance
The addition of the Bitwise NOT operator completes the set of binary operations available on the calculator. This is fundamental for users who require comprehensive tools for learning or debugging binary arithmetic, enhancing the overall utility of the calculator.

## Testing
The function has been tested with various binary inputs to ensure accurate inversion of binary digits. The following test cases were used:
- Input: `1100`, Expected Output: `0011`
- Input: `101010`, Expected Output: `010101`

## Requesting Review
I would appreciate a review from @Alitindrawan24  to discuss the feasibility and further improvements needed for this feature.

Thank you for considering this addition to the Binary Calculator.

### CODE REVIEW

**Comment by Alitindrawan24** [comment]
Can you fix the Conflict @Satyasn01

**Comment by Satyasn01** [comment]
#103 
Opened a new PR

**Comment by Alitindrawan24** [comment]
Your PR contain conflict after I'm merged other PR, plz solve the conflict first @Satyasn01

**Comment by Satyasn01** [comment]
#111

**Pull request closed without merging**
