### PR TITLE
Added Binary to Octal conversion 

### PR DESCRIPTION
**Pull request by vaishnavibn14**
Added Binary to Octal conversion.

 
Screenshot (27)

https://github.com/Alitindrawan24/Binary-Calculator/issues/49

### CODE REVIEW

**Comment by Alitindrawan24** [comment]
After merging mayor fix, conflict happen in this PR. Can you fix it ? @vaishnavibn14

**Comment by vaishnavibn14** [comment]
Hi @Alitindrawan24 , 

 I have updated the files to resolved the conflicts.
 
Screenshot (29)

**Comment by Alitindrawan24** [comment]
> Hi @Alitindrawan24 ,
> 
> I have updated the files to resolved the conflicts.
> 
> Screenshot (29)

Sorry but the conflict still exists on the PR

**Comment by vaishnavibn14** [comment]
Hi @Alitindrawan24 ,
conflict is resolved.

**Pull request merged**
