### PR TITLE
# add copyright  footer

### PR DESCRIPTION
**Pull request by REHAN-18**
1-add the footer of the copyright & enhance the ui

### CODE REVIEW

**Comment by Alitindrawan24** [comment]
@REHAN-18 this PR contain conflict after I merge other PR please solve it first and also please add the issue number on description

**Comment by REHAN-18** [comment]
ok done now see #133

**Comment by REHAN-18** [comment]
@ Alitindrawan24 pls see I have resolve the conflict.

**Comment by REHAN-18** [comment]
@Alitindrawan24  bro I ve fix the  conflict pls check it

**Pull request merged**
